version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
      - "3035:3035"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: "true"
